sonar.issue.ignore.multicriteria=e1

# S3267: Loops should be simplified with LINQ expressions
sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S3267
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.cs
