/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 3.5.0.0
 */
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using Hime.Redist;
using Hime.Redist.Lexer;

namespace Gehtsoft.EF.Db.SqlDb.Sql
{
	/// <summary>
	/// Represents a lexer
	/// </summary>
	[GeneratedCodeAttribute("Hime.SDK", "3.5.0.0")]
	public class SqlLexer : ContextFreeLexer
	{
		/// <summary>
		/// The automaton for this lexer
		/// </summary>
		private static readonly Automaton commonAutomaton = Automaton.Find(typeof(SqlLexer), "SqlLexer.bin");
		/// <summary>
		/// Contains the constant IDs for the terminals for this lexer
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "3.5.0.0")]
		public class ID
		{
			/// <summary>
			/// The unique identifier for terminal NEW_LINE
			/// </summary>
			public const int TerminalNewLine = 0x0003;
			/// <summary>
			/// The unique identifier for terminal WHITE_SPACE
			/// </summary>
			public const int TerminalWhiteSpace = 0x0004;
			/// <summary>
			/// The unique identifier for terminal INT
			/// </summary>
			public const int TerminalInt = 0x0005;
			/// <summary>
			/// The unique identifier for terminal REAL
			/// </summary>
			public const int TerminalReal = 0x0006;
			/// <summary>
			/// The unique identifier for terminal STRINGDQ
			/// </summary>
			public const int TerminalStringdq = 0x0007;
			/// <summary>
			/// The unique identifier for terminal STRINGSQ
			/// </summary>
			public const int TerminalStringsq = 0x0008;
			/// <summary>
			/// The unique identifier for terminal COMMENT_LINE
			/// </summary>
			public const int TerminalCommentLine = 0x0009;
			/// <summary>
			/// The unique identifier for terminal IDENTIFIER
			/// </summary>
			public const int TerminalIdentifier = 0x000A;
			/// <summary>
			/// The unique identifier for terminal SEPARATOR
			/// </summary>
			public const int TerminalSeparator = 0x000B;
			/// <summary>
			/// The unique identifier for terminal GLOBAL_PARAMETER_NAME
			/// </summary>
			public const int TerminalGlobalParameterName = 0x000C;
			/// <summary>
			/// The unique identifier for terminal ASSIGN
			/// </summary>
			public const int TerminalAssign = 0x000D;
		}
		/// <summary>
		/// Contains the constant IDs for the contexts for this lexer
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "3.5.0.0")]
		public class Context
		{
			/// <summary>
			/// The unique identifier for the default context
			/// </summary>
			public const int Default = 0;
		}
		/// <summary>
		/// The collection of terminals matched by this lexer
		/// </summary>
		/// <remarks>
		/// The terminals are in an order consistent with the automaton,
		/// so that terminal indices in the automaton can be used to retrieve the terminals in this table
		/// </remarks>
		private static readonly Symbol[] terminals = {
			new Symbol(0x0001, "ε"),
			new Symbol(0x0002, "$"),
			new Symbol(0x0003, "NEW_LINE"),
			new Symbol(0x0004, "WHITE_SPACE"),
			new Symbol(0x0005, "INT"),
			new Symbol(0x0006, "REAL"),
			new Symbol(0x0007, "STRINGDQ"),
			new Symbol(0x0008, "STRINGSQ"),
			new Symbol(0x0009, "COMMENT_LINE"),
			new Symbol(0x000A, "IDENTIFIER"),
			new Symbol(0x000B, "SEPARATOR"),
			new Symbol(0x000C, "GLOBAL_PARAMETER_NAME"),
			new Symbol(0x000D, "ASSIGN"),
			new Symbol(0x00A4, "NULL"),
			new Symbol(0x00A5, "TRUE"),
			new Symbol(0x00A6, "FALSE"),
			new Symbol(0x00A7, "DATE"),
			new Symbol(0x00A8, "DATETIME"),
			new Symbol(0x00A9, ";"),
			new Symbol(0x00AB, "-"),
			new Symbol(0x00AC, "+"),
			new Symbol(0x00AD, "*"),
			new Symbol(0x00AE, "/"),
			new Symbol(0x00AF, "||"),
			new Symbol(0x00B0, "="),
			new Symbol(0x00B1, "<>"),
			new Symbol(0x00B2, ">"),
			new Symbol(0x00B3, ">="),
			new Symbol(0x00B4, "<"),
			new Symbol(0x00B5, "<="),
			new Symbol(0x00B6, "LIKE"),
			new Symbol(0x00B7, "NOT"),
			new Symbol(0x00B8, "IN"),
			new Symbol(0x00B9, "IS"),
			new Symbol(0x00BA, ","),
			new Symbol(0x00BC, "("),
			new Symbol(0x00BD, ")"),
			new Symbol(0x00BE, "ABS"),
			new Symbol(0x00BF, "TOSTRING"),
			new Symbol(0x00C0, "TOINT"),
			new Symbol(0x00C1, "TODOUBLE"),
			new Symbol(0x00C2, "TODATE"),
			new Symbol(0x00C3, "TOTIMESTAMP"),
			new Symbol(0x00C4, "TRIM"),
			new Symbol(0x00C5, "LTRIM"),
			new Symbol(0x00C6, "RTRIM"),
			new Symbol(0x00C7, "UPPER"),
			new Symbol(0x00C8, "LOWER"),
			new Symbol(0x00C9, "CONTAINS"),
			new Symbol(0x00CA, "ENDSWITH"),
			new Symbol(0x00CB, "STARTSWITH"),
			new Symbol(0x00CC, "LEADING"),
			new Symbol(0x00CD, "TRAILING"),
			new Symbol(0x00CE, "BOTH"),
			new Symbol(0x00CF, "LAST_RESULT"),
			new Symbol(0x00D0, "ROWS_COUNT"),
			new Symbol(0x00D1, "GET_ROW"),
			new Symbol(0x00D2, "GET_FIELD"),
			new Symbol(0x00D3, "NEW_ROWSET"),
			new Symbol(0x00D4, "NEW_ROW"),
			new Symbol(0x00D5, "FETCH"),
			new Symbol(0x00D6, "STRING"),
			new Symbol(0x00D7, "INTEGER"),
			new Symbol(0x00D8, "DOUBLE"),
			new Symbol(0x00D9, "BOOLEAN"),
			new Symbol(0x00DA, "ROW"),
			new Symbol(0x00DB, "ROWSET"),
			new Symbol(0x00DC, "AS"),
			new Symbol(0x00DE, "AND"),
			new Symbol(0x00DF, "OR"),
			new Symbol(0x00E0, "DISTINCT"),
			new Symbol(0x00E1, "ALL"),
			new Symbol(0x00E2, "COUNT"),
			new Symbol(0x00E3, "MAX"),
			new Symbol(0x00E4, "MIN"),
			new Symbol(0x00E5, "AVG"),
			new Symbol(0x00E6, "SUM"),
			new Symbol(0x00E7, "COUNT(*)"),
			new Symbol(0x00E9, "."),
			new Symbol(0x00EA, "WHERE"),
			new Symbol(0x00EB, "FROM"),
			new Symbol(0x00ED, "AUTO"),
			new Symbol(0x00EE, "JOIN"),
			new Symbol(0x00EF, "INNER"),
			new Symbol(0x00F0, "OUTER"),
			new Symbol(0x00F1, "LEFT"),
			new Symbol(0x00F2, "RIGHT"),
			new Symbol(0x00F3, "FULL"),
			new Symbol(0x00F4, "ON"),
			new Symbol(0x00F5, "SELECT"),
			new Symbol(0x00F6, "ORDER BY"),
			new Symbol(0x00F8, "ASC"),
			new Symbol(0x00F9, "DESC"),
			new Symbol(0x00FA, "GROUP BY"),
			new Symbol(0x00FC, "LIMIT"),
			new Symbol(0x00FD, "OFFSET"),
			new Symbol(0x00FE, "INSERT"),
			new Symbol(0x00FF, "INTO"),
			new Symbol(0x0102, "VALUES"),
			new Symbol(0x0103, "UPDATE"),
			new Symbol(0x0104, "SET"),
			new Symbol(0x0106, "DELETE"),
			new Symbol(0x0108, "IMPORT"),
			new Symbol(0x0109, "DECLARE"),
			new Symbol(0x010B, "EXIT"),
			new Symbol(0x010C, "WITH"),
			new Symbol(0x010E, "IF"),
			new Symbol(0x010F, "THEN"),
			new Symbol(0x0110, "ELSIF"),
			new Symbol(0x0112, "ELSE"),
			new Symbol(0x0113, "END"),
			new Symbol(0x0114, "WHILE"),
			new Symbol(0x0115, "LOOP"),
			new Symbol(0x0116, "BREAK"),
			new Symbol(0x0117, "CONTINUE"),
			new Symbol(0x0118, "FOR"),
			new Symbol(0x0119, "NEXT"),
			new Symbol(0x011A, "SWITCH"),
			new Symbol(0x011B, "CASE"),
			new Symbol(0x011C, ":"),
			new Symbol(0x011E, "OTHERWISE"),
			new Symbol(0x011F, "ADD"),
			new Symbol(0x0120, "FIELD"),
			new Symbol(0x0121, "TO"),
			new Symbol(0x0122, "CURSOR"),
			new Symbol(0x0123, "OPEN"),
			new Symbol(0x0124, "CLOSE") };
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public SqlLexer(string input) : base(commonAutomaton, terminals, 0x000B, input) {}
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public SqlLexer(TextReader input) : base(commonAutomaton, terminals, 0x000B, input) {}
	}
}
