/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 3.5.0.0
 */
using System.CodeDom.Compiler;
using System.Collections.Generic;
using Hime.Redist;
using Hime.Redist.Parsers;

namespace Gehtsoft.EF.Db.SqlDb.Sql
{
	/// <summary>
	/// Represents a parser
	/// </summary>
	[GeneratedCodeAttribute("Hime.SDK", "3.5.0.0")]
	public class SqlParser : RNGLRParser
	{
		/// <summary>
		/// The automaton for this parser
		/// </summary>
		private static readonly RNGLRAutomaton commonAutomaton = RNGLRAutomaton.Find(typeof(SqlParser), "SqlParser.bin");
		/// <summary>
		/// Contains the constant IDs for the variables and virtuals in this parser
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "3.5.0.0")]
		public class ID
		{
			/// <summary>
			/// The unique identifier for variable NULL
			/// </summary>
			public const int VariableNull = 0x000C;
			/// <summary>
			/// The unique identifier for variable BOOLEAN_TRUE
			/// </summary>
			public const int VariableBooleanTrue = 0x000D;
			/// <summary>
			/// The unique identifier for variable BOOLEAN_FALSE
			/// </summary>
			public const int VariableBooleanFalse = 0x000E;
			/// <summary>
			/// The unique identifier for variable BOOLEAN_CONST
			/// </summary>
			public const int VariableBooleanConst = 0x000F;
			/// <summary>
			/// The unique identifier for variable STRING_CONST
			/// </summary>
			public const int VariableStringConst = 0x0010;
			/// <summary>
			/// The unique identifier for variable NUMBER_CONST
			/// </summary>
			public const int VariableNumberConst = 0x0011;
			/// <summary>
			/// The unique identifier for variable DATE_CONST
			/// </summary>
			public const int VariableDateConst = 0x0012;
			/// <summary>
			/// The unique identifier for variable CONSTANT
			/// </summary>
			public const int VariableConstant = 0x0013;
			/// <summary>
			/// The unique identifier for variable EOS
			/// </summary>
			public const int VariableEos = 0x0014;
			/// <summary>
			/// The unique identifier for variable NOP
			/// </summary>
			public const int VariableNop = 0x0015;
			/// <summary>
			/// The unique identifier for variable MINUS_OP
			/// </summary>
			public const int VariableMinusOp = 0x0016;
			/// <summary>
			/// The unique identifier for variable PLUS_OP
			/// </summary>
			public const int VariablePlusOp = 0x0017;
			/// <summary>
			/// The unique identifier for variable MUL_OP
			/// </summary>
			public const int VariableMulOp = 0x0018;
			/// <summary>
			/// The unique identifier for variable DIV_OP
			/// </summary>
			public const int VariableDivOp = 0x0019;
			/// <summary>
			/// The unique identifier for variable CONCAT_OP
			/// </summary>
			public const int VariableConcatOp = 0x001A;
			/// <summary>
			/// The unique identifier for variable EQ_OP
			/// </summary>
			public const int VariableEqOp = 0x001B;
			/// <summary>
			/// The unique identifier for variable NEQ_OP
			/// </summary>
			public const int VariableNeqOp = 0x001C;
			/// <summary>
			/// The unique identifier for variable GT_OP
			/// </summary>
			public const int VariableGtOp = 0x001D;
			/// <summary>
			/// The unique identifier for variable GE_OP
			/// </summary>
			public const int VariableGeOp = 0x001E;
			/// <summary>
			/// The unique identifier for variable LT_OP
			/// </summary>
			public const int VariableLtOp = 0x001F;
			/// <summary>
			/// The unique identifier for variable LE_OP
			/// </summary>
			public const int VariableLeOp = 0x0020;
			/// <summary>
			/// The unique identifier for variable CALL_ARGS
			/// </summary>
			public const int VariableCallArgs = 0x0021;
			/// <summary>
			/// The unique identifier for variable CALL_BRACKET
			/// </summary>
			public const int VariableCallBracket = 0x0022;
			/// <summary>
			/// The unique identifier for variable FUNC_NAME
			/// </summary>
			public const int VariableFuncName = 0x0023;
			/// <summary>
			/// The unique identifier for variable CALL
			/// </summary>
			public const int VariableCall = 0x0024;
			/// <summary>
			/// The unique identifier for variable TRIM_LEADING
			/// </summary>
			public const int VariableTrimLeading = 0x0025;
			/// <summary>
			/// The unique identifier for variable TRIM_TRAILING
			/// </summary>
			public const int VariableTrimTrailing = 0x0026;
			/// <summary>
			/// The unique identifier for variable TRIM_BOTH
			/// </summary>
			public const int VariableTrimBoth = 0x0027;
			/// <summary>
			/// The unique identifier for variable TRIM_SPECIFICATION
			/// </summary>
			public const int VariableTrimSpecification = 0x0028;
			/// <summary>
			/// The unique identifier for variable TRIM_CALL
			/// </summary>
			public const int VariableTrimCall = 0x0029;
			/// <summary>
			/// The unique identifier for variable FUNC_CALL
			/// </summary>
			public const int VariableFuncCall = 0x002A;
			/// <summary>
			/// The unique identifier for variable BRACKET_EXPR
			/// </summary>
			public const int VariableBracketExpr = 0x002B;
			/// <summary>
			/// The unique identifier for variable SIMPLE_EXPR
			/// </summary>
			public const int VariableSimpleExpr = 0x002C;
			/// <summary>
			/// The unique identifier for variable UNARY_EXPR
			/// </summary>
			public const int VariableUnaryExpr = 0x002D;
			/// <summary>
			/// The unique identifier for variable MUL_EXPR
			/// </summary>
			public const int VariableMulExpr = 0x002E;
			/// <summary>
			/// The unique identifier for variable ADD_EXPR
			/// </summary>
			public const int VariableAddExpr = 0x002F;
			/// <summary>
			/// The unique identifier for variable CONCAT_EXPR
			/// </summary>
			public const int VariableConcatExpr = 0x0030;
			/// <summary>
			/// The unique identifier for variable COM_EXPR
			/// </summary>
			public const int VariableComExpr = 0x0031;
			/// <summary>
			/// The unique identifier for variable REL_EXPR
			/// </summary>
			public const int VariableRelExpr = 0x0032;
			/// <summary>
			/// The unique identifier for variable NOT_OP
			/// </summary>
			public const int VariableNotOp = 0x0033;
			/// <summary>
			/// The unique identifier for variable AND_OP
			/// </summary>
			public const int VariableAndOp = 0x0034;
			/// <summary>
			/// The unique identifier for variable OR_OP
			/// </summary>
			public const int VariableOrOp = 0x0035;
			/// <summary>
			/// The unique identifier for variable UX_BOOL_EXPR
			/// </summary>
			public const int VariableUxBoolExpr = 0x0036;
			/// <summary>
			/// The unique identifier for variable AND_BOOL_EXPR
			/// </summary>
			public const int VariableAndBoolExpr = 0x0037;
			/// <summary>
			/// The unique identifier for variable OR_BOOL_EXPR
			/// </summary>
			public const int VariableOrBoolExpr = 0x0038;
			/// <summary>
			/// The unique identifier for variable EXPR
			/// </summary>
			public const int VariableExpr = 0x0039;
			/// <summary>
			/// The unique identifier for variable BOOL_EXPR
			/// </summary>
			public const int VariableBoolExpr = 0x003A;
			/// <summary>
			/// The unique identifier for variable SET_QUANTIFIER
			/// </summary>
			public const int VariableSetQuantifier = 0x003B;
			/// <summary>
			/// The unique identifier for variable ASRERISK
			/// </summary>
			public const int VariableAsrerisk = 0x003C;
			/// <summary>
			/// The unique identifier for variable AGGR_CALL_BRACKET
			/// </summary>
			public const int VariableAggrCallBracket = 0x003D;
			/// <summary>
			/// The unique identifier for variable AGGR_FUNC
			/// </summary>
			public const int VariableAggrFunc = 0x003E;
			/// <summary>
			/// The unique identifier for variable AGGR_COUNT_ALL
			/// </summary>
			public const int VariableAggrCountAll = 0x003F;
			/// <summary>
			/// The unique identifier for variable AGGR_CALL
			/// </summary>
			public const int VariableAggrCall = 0x0040;
			/// <summary>
			/// The unique identifier for variable SELECT_SUBLIST
			/// </summary>
			public const int VariableSelectSublist = 0x0041;
			/// <summary>
			/// The unique identifier for variable EXPR_ALIAS
			/// </summary>
			public const int VariableExprAlias = 0x0042;
			/// <summary>
			/// The unique identifier for variable FIELD
			/// </summary>
			public const int VariableField = 0x0043;
			/// <summary>
			/// The unique identifier for variable SELECT_LIST
			/// </summary>
			public const int VariableSelectList = 0x0044;
			/// <summary>
			/// The unique identifier for variable TABLE_EXPRESSION
			/// </summary>
			public const int VariableTableExpression = 0x0045;
			/// <summary>
			/// The unique identifier for variable WHERE_CLAUSE
			/// </summary>
			public const int VariableWhereClause = 0x0046;
			/// <summary>
			/// The unique identifier for variable FROM_CLAUSE
			/// </summary>
			public const int VariableFromClause = 0x0047;
			/// <summary>
			/// The unique identifier for variable TABLE_REFERENCE_LIST
			/// </summary>
			public const int VariableTableReferenceList = 0x0048;
			/// <summary>
			/// The unique identifier for variable TABLE_REFERENCE
			/// </summary>
			public const int VariableTableReference = 0x0049;
			/// <summary>
			/// The unique identifier for variable TABLE_PRIMARY
			/// </summary>
			public const int VariableTablePrimary = 0x004A;
			/// <summary>
			/// The unique identifier for variable JOINED_TABLE
			/// </summary>
			public const int VariableJoinedTable = 0x004B;
			/// <summary>
			/// The unique identifier for variable AUTO_JOIN
			/// </summary>
			public const int VariableAutoJoin = 0x004C;
			/// <summary>
			/// The unique identifier for variable QUALIFIED_JOIN
			/// </summary>
			public const int VariableQualifiedJoin = 0x004D;
			/// <summary>
			/// The unique identifier for variable JOIN_TYPE
			/// </summary>
			public const int VariableJoinType = 0x004E;
			/// <summary>
			/// The unique identifier for variable OUTER_JOIN_TYPE
			/// </summary>
			public const int VariableOuterJoinType = 0x004F;
			/// <summary>
			/// The unique identifier for variable JOIN_SPECIFICATION
			/// </summary>
			public const int VariableJoinSpecification = 0x0050;
			/// <summary>
			/// The unique identifier for variable JOIN_CONDITION
			/// </summary>
			public const int VariableJoinCondition = 0x0051;
			/// <summary>
			/// The unique identifier for variable SELECT
			/// </summary>
			public const int VariableSelect = 0x0052;
			/// <summary>
			/// The unique identifier for variable ORDER_BY
			/// </summary>
			public const int VariableOrderBy = 0x0053;
			/// <summary>
			/// The unique identifier for variable SORT_SPECIFICATION_LIST
			/// </summary>
			public const int VariableSortSpecificationList = 0x0054;
			/// <summary>
			/// The unique identifier for variable SORT_SPECIFICATION
			/// </summary>
			public const int VariableSortSpecification = 0x0055;
			/// <summary>
			/// The unique identifier for variable ORDERING_SPECIFICATION
			/// </summary>
			public const int VariableOrderingSpecification = 0x0056;
			/// <summary>
			/// The unique identifier for variable GROUP_BY
			/// </summary>
			public const int VariableGroupBy = 0x0057;
			/// <summary>
			/// The unique identifier for variable GROUP_SPECIFICATION_LIST
			/// </summary>
			public const int VariableGroupSpecificationList = 0x0058;
			/// <summary>
			/// The unique identifier for variable GROUP_SPECIFICATION
			/// </summary>
			public const int VariableGroupSpecification = 0x0059;
			/// <summary>
			/// The unique identifier for variable LIMIT_OFFSET
			/// </summary>
			public const int VariableLimitOffset = 0x005A;
			/// <summary>
			/// The unique identifier for variable LIMIT
			/// </summary>
			public const int VariableLimit = 0x005B;
			/// <summary>
			/// The unique identifier for variable OFFSET
			/// </summary>
			public const int VariableOffset = 0x005C;
			/// <summary>
			/// The unique identifier for variable STATEMENT
			/// </summary>
			public const int VariableStatement = 0x005D;
			/// <summary>
			/// The unique identifier for variable ROOT
			/// </summary>
			public const int VariableRoot = 0x005E;
		}
		/// <summary>
		/// The collection of variables matched by this parser
		/// </summary>
		/// <remarks>
		/// The variables are in an order consistent with the automaton,
		/// so that variable indices in the automaton can be used to retrieve the variables in this table
		/// </remarks>
		private static readonly Symbol[] variables = {
			new Symbol(0x000C, "NULL"), 
			new Symbol(0x000D, "BOOLEAN_TRUE"), 
			new Symbol(0x000E, "BOOLEAN_FALSE"), 
			new Symbol(0x000F, "BOOLEAN_CONST"), 
			new Symbol(0x0010, "STRING_CONST"), 
			new Symbol(0x0011, "NUMBER_CONST"), 
			new Symbol(0x0012, "DATE_CONST"), 
			new Symbol(0x0013, "CONSTANT"), 
			new Symbol(0x0014, "EOS"), 
			new Symbol(0x0015, "NOP"), 
			new Symbol(0x0016, "MINUS_OP"), 
			new Symbol(0x0017, "PLUS_OP"), 
			new Symbol(0x0018, "MUL_OP"), 
			new Symbol(0x0019, "DIV_OP"), 
			new Symbol(0x001A, "CONCAT_OP"), 
			new Symbol(0x001B, "EQ_OP"), 
			new Symbol(0x001C, "NEQ_OP"), 
			new Symbol(0x001D, "GT_OP"), 
			new Symbol(0x001E, "GE_OP"), 
			new Symbol(0x001F, "LT_OP"), 
			new Symbol(0x0020, "LE_OP"), 
			new Symbol(0x0021, "CALL_ARGS"), 
			new Symbol(0x0022, "CALL_BRACKET"), 
			new Symbol(0x0023, "FUNC_NAME"), 
			new Symbol(0x0024, "CALL"), 
			new Symbol(0x0025, "TRIM_LEADING"), 
			new Symbol(0x0026, "TRIM_TRAILING"), 
			new Symbol(0x0027, "TRIM_BOTH"), 
			new Symbol(0x0028, "TRIM_SPECIFICATION"), 
			new Symbol(0x0029, "TRIM_CALL"), 
			new Symbol(0x002A, "FUNC_CALL"), 
			new Symbol(0x002B, "BRACKET_EXPR"), 
			new Symbol(0x002C, "SIMPLE_EXPR"), 
			new Symbol(0x002D, "UNARY_EXPR"), 
			new Symbol(0x002E, "MUL_EXPR"), 
			new Symbol(0x002F, "ADD_EXPR"), 
			new Symbol(0x0030, "CONCAT_EXPR"), 
			new Symbol(0x0031, "COM_EXPR"), 
			new Symbol(0x0032, "REL_EXPR"), 
			new Symbol(0x0033, "NOT_OP"), 
			new Symbol(0x0034, "AND_OP"), 
			new Symbol(0x0035, "OR_OP"), 
			new Symbol(0x0036, "UX_BOOL_EXPR"), 
			new Symbol(0x0037, "AND_BOOL_EXPR"), 
			new Symbol(0x0038, "OR_BOOL_EXPR"), 
			new Symbol(0x0039, "EXPR"), 
			new Symbol(0x003A, "BOOL_EXPR"), 
			new Symbol(0x003B, "SET_QUANTIFIER"), 
			new Symbol(0x003C, "ASRERISK"), 
			new Symbol(0x003D, "AGGR_CALL_BRACKET"), 
			new Symbol(0x003E, "AGGR_FUNC"), 
			new Symbol(0x003F, "AGGR_COUNT_ALL"), 
			new Symbol(0x0040, "AGGR_CALL"), 
			new Symbol(0x0041, "SELECT_SUBLIST"), 
			new Symbol(0x0042, "EXPR_ALIAS"), 
			new Symbol(0x0043, "FIELD"), 
			new Symbol(0x0044, "SELECT_LIST"), 
			new Symbol(0x0045, "TABLE_EXPRESSION"), 
			new Symbol(0x0046, "WHERE_CLAUSE"), 
			new Symbol(0x0047, "FROM_CLAUSE"), 
			new Symbol(0x0048, "TABLE_REFERENCE_LIST"), 
			new Symbol(0x0049, "TABLE_REFERENCE"), 
			new Symbol(0x004A, "TABLE_PRIMARY"), 
			new Symbol(0x004B, "JOINED_TABLE"), 
			new Symbol(0x004C, "AUTO_JOIN"), 
			new Symbol(0x004D, "QUALIFIED_JOIN"), 
			new Symbol(0x004E, "JOIN_TYPE"), 
			new Symbol(0x004F, "OUTER_JOIN_TYPE"), 
			new Symbol(0x0050, "JOIN_SPECIFICATION"), 
			new Symbol(0x0051, "JOIN_CONDITION"), 
			new Symbol(0x0052, "SELECT"), 
			new Symbol(0x0053, "ORDER_BY"), 
			new Symbol(0x0054, "SORT_SPECIFICATION_LIST"), 
			new Symbol(0x0055, "SORT_SPECIFICATION"), 
			new Symbol(0x0056, "ORDERING_SPECIFICATION"), 
			new Symbol(0x0057, "GROUP_BY"), 
			new Symbol(0x0058, "GROUP_SPECIFICATION_LIST"), 
			new Symbol(0x0059, "GROUP_SPECIFICATION"), 
			new Symbol(0x005A, "LIMIT_OFFSET"), 
			new Symbol(0x005B, "LIMIT"), 
			new Symbol(0x005C, "OFFSET"), 
			new Symbol(0x005D, "STATEMENT"), 
			new Symbol(0x005E, "ROOT"), 
			new Symbol(0x0064, "__V100"), 
			new Symbol(0x0071, "__V113"), 
			new Symbol(0x0085, "__V133"), 
			new Symbol(0x008A, "__V138"), 
			new Symbol(0x0095, "__V149"), 
			new Symbol(0x0099, "__V153"), 
			new Symbol(0x009C, "__V156"), 
			new Symbol(0x009D, "__VAxiom") };
		/// <summary>
		/// The collection of virtuals matched by this parser
		/// </summary>
		/// <remarks>
		/// The virtuals are in an order consistent with the automaton,
		/// so that virtual indices in the automaton can be used to retrieve the virtuals in this table
		/// </remarks>
		private static readonly Symbol[] virtuals = {
 };
		/// <summary>
		/// Initializes a new instance of the parser
		/// </summary>
		/// <param name="lexer">The input lexer</param>
		public SqlParser(SqlLexer lexer) : base (commonAutomaton, variables, virtuals, null, lexer) { }

		/// <summary>
		/// Visitor interface
		/// </summary>
		[GeneratedCodeAttribute("Hime.SDK", "3.5.0.0")]
		public class Visitor
		{
			public virtual void OnTerminalNewLine(ASTNode node) {}
			public virtual void OnTerminalWhiteSpace(ASTNode node) {}
			public virtual void OnTerminalInteger(ASTNode node) {}
			public virtual void OnTerminalReal(ASTNode node) {}
			public virtual void OnTerminalStringdq(ASTNode node) {}
			public virtual void OnTerminalStringsq(ASTNode node) {}
			public virtual void OnTerminalCommentLine(ASTNode node) {}
			public virtual void OnTerminalIdentifier(ASTNode node) {}
			public virtual void OnTerminalSeparator(ASTNode node) {}
			public virtual void OnVariableNull(ASTNode node) {}
			public virtual void OnVariableBooleanTrue(ASTNode node) {}
			public virtual void OnVariableBooleanFalse(ASTNode node) {}
			public virtual void OnVariableBooleanConst(ASTNode node) {}
			public virtual void OnVariableStringConst(ASTNode node) {}
			public virtual void OnVariableNumberConst(ASTNode node) {}
			public virtual void OnVariableDateConst(ASTNode node) {}
			public virtual void OnVariableConstant(ASTNode node) {}
			public virtual void OnVariableEos(ASTNode node) {}
			public virtual void OnVariableNop(ASTNode node) {}
			public virtual void OnVariableMinusOp(ASTNode node) {}
			public virtual void OnVariablePlusOp(ASTNode node) {}
			public virtual void OnVariableMulOp(ASTNode node) {}
			public virtual void OnVariableDivOp(ASTNode node) {}
			public virtual void OnVariableConcatOp(ASTNode node) {}
			public virtual void OnVariableEqOp(ASTNode node) {}
			public virtual void OnVariableNeqOp(ASTNode node) {}
			public virtual void OnVariableGtOp(ASTNode node) {}
			public virtual void OnVariableGeOp(ASTNode node) {}
			public virtual void OnVariableLtOp(ASTNode node) {}
			public virtual void OnVariableLeOp(ASTNode node) {}
			public virtual void OnVariableCallArgs(ASTNode node) {}
			public virtual void OnVariableCallBracket(ASTNode node) {}
			public virtual void OnVariableFuncName(ASTNode node) {}
			public virtual void OnVariableCall(ASTNode node) {}
			public virtual void OnVariableTrimLeading(ASTNode node) {}
			public virtual void OnVariableTrimTrailing(ASTNode node) {}
			public virtual void OnVariableTrimBoth(ASTNode node) {}
			public virtual void OnVariableTrimSpecification(ASTNode node) {}
			public virtual void OnVariableTrimCall(ASTNode node) {}
			public virtual void OnVariableFuncCall(ASTNode node) {}
			public virtual void OnVariableBracketExpr(ASTNode node) {}
			public virtual void OnVariableSimpleExpr(ASTNode node) {}
			public virtual void OnVariableUnaryExpr(ASTNode node) {}
			public virtual void OnVariableMulExpr(ASTNode node) {}
			public virtual void OnVariableAddExpr(ASTNode node) {}
			public virtual void OnVariableConcatExpr(ASTNode node) {}
			public virtual void OnVariableComExpr(ASTNode node) {}
			public virtual void OnVariableRelExpr(ASTNode node) {}
			public virtual void OnVariableNotOp(ASTNode node) {}
			public virtual void OnVariableAndOp(ASTNode node) {}
			public virtual void OnVariableOrOp(ASTNode node) {}
			public virtual void OnVariableUxBoolExpr(ASTNode node) {}
			public virtual void OnVariableAndBoolExpr(ASTNode node) {}
			public virtual void OnVariableOrBoolExpr(ASTNode node) {}
			public virtual void OnVariableExpr(ASTNode node) {}
			public virtual void OnVariableBoolExpr(ASTNode node) {}
			public virtual void OnVariableSetQuantifier(ASTNode node) {}
			public virtual void OnVariableAsrerisk(ASTNode node) {}
			public virtual void OnVariableAggrCallBracket(ASTNode node) {}
			public virtual void OnVariableAggrFunc(ASTNode node) {}
			public virtual void OnVariableAggrCountAll(ASTNode node) {}
			public virtual void OnVariableAggrCall(ASTNode node) {}
			public virtual void OnVariableSelectSublist(ASTNode node) {}
			public virtual void OnVariableExprAlias(ASTNode node) {}
			public virtual void OnVariableField(ASTNode node) {}
			public virtual void OnVariableSelectList(ASTNode node) {}
			public virtual void OnVariableTableExpression(ASTNode node) {}
			public virtual void OnVariableWhereClause(ASTNode node) {}
			public virtual void OnVariableFromClause(ASTNode node) {}
			public virtual void OnVariableTableReferenceList(ASTNode node) {}
			public virtual void OnVariableTableReference(ASTNode node) {}
			public virtual void OnVariableTablePrimary(ASTNode node) {}
			public virtual void OnVariableJoinedTable(ASTNode node) {}
			public virtual void OnVariableAutoJoin(ASTNode node) {}
			public virtual void OnVariableQualifiedJoin(ASTNode node) {}
			public virtual void OnVariableJoinType(ASTNode node) {}
			public virtual void OnVariableOuterJoinType(ASTNode node) {}
			public virtual void OnVariableJoinSpecification(ASTNode node) {}
			public virtual void OnVariableJoinCondition(ASTNode node) {}
			public virtual void OnVariableSelect(ASTNode node) {}
			public virtual void OnVariableOrderBy(ASTNode node) {}
			public virtual void OnVariableSortSpecificationList(ASTNode node) {}
			public virtual void OnVariableSortSpecification(ASTNode node) {}
			public virtual void OnVariableOrderingSpecification(ASTNode node) {}
			public virtual void OnVariableGroupBy(ASTNode node) {}
			public virtual void OnVariableGroupSpecificationList(ASTNode node) {}
			public virtual void OnVariableGroupSpecification(ASTNode node) {}
			public virtual void OnVariableLimitOffset(ASTNode node) {}
			public virtual void OnVariableLimit(ASTNode node) {}
			public virtual void OnVariableOffset(ASTNode node) {}
			public virtual void OnVariableStatement(ASTNode node) {}
			public virtual void OnVariableRoot(ASTNode node) {}
		}

		/// <summary>
		/// Walk the AST of a result using a visitor
		/// <param name="result">The parse result</param>
		/// <param name="visitor">The visitor to use</param>
		/// </summary>
		public static void Visit(ParseResult result, Visitor visitor)
		{
			VisitASTNode(result.Root, visitor);
		}

		/// <summary>
		/// Walk the sub-AST from the specified node using a visitor
		/// </summary>
		/// <param name="node">The AST node to start from</param>
		/// <param name="visitor">The visitor to use</param>
		public static void VisitASTNode(ASTNode node, Visitor visitor)
		{
			for (int i = 0; i < node.Children.Count; i++)
				VisitASTNode(node.Children[i], visitor);
			switch(node.Symbol.ID)
			{
				case 0x0003: visitor.OnTerminalNewLine(node); break;
				case 0x0004: visitor.OnTerminalWhiteSpace(node); break;
				case 0x0005: visitor.OnTerminalInteger(node); break;
				case 0x0006: visitor.OnTerminalReal(node); break;
				case 0x0007: visitor.OnTerminalStringdq(node); break;
				case 0x0008: visitor.OnTerminalStringsq(node); break;
				case 0x0009: visitor.OnTerminalCommentLine(node); break;
				case 0x000A: visitor.OnTerminalIdentifier(node); break;
				case 0x000B: visitor.OnTerminalSeparator(node); break;
				case 0x000C: visitor.OnVariableNull(node); break;
				case 0x000D: visitor.OnVariableBooleanTrue(node); break;
				case 0x000E: visitor.OnVariableBooleanFalse(node); break;
				case 0x000F: visitor.OnVariableBooleanConst(node); break;
				case 0x0010: visitor.OnVariableStringConst(node); break;
				case 0x0011: visitor.OnVariableNumberConst(node); break;
				case 0x0012: visitor.OnVariableDateConst(node); break;
				case 0x0013: visitor.OnVariableConstant(node); break;
				case 0x0014: visitor.OnVariableEos(node); break;
				case 0x0015: visitor.OnVariableNop(node); break;
				case 0x0016: visitor.OnVariableMinusOp(node); break;
				case 0x0017: visitor.OnVariablePlusOp(node); break;
				case 0x0018: visitor.OnVariableMulOp(node); break;
				case 0x0019: visitor.OnVariableDivOp(node); break;
				case 0x001A: visitor.OnVariableConcatOp(node); break;
				case 0x001B: visitor.OnVariableEqOp(node); break;
				case 0x001C: visitor.OnVariableNeqOp(node); break;
				case 0x001D: visitor.OnVariableGtOp(node); break;
				case 0x001E: visitor.OnVariableGeOp(node); break;
				case 0x001F: visitor.OnVariableLtOp(node); break;
				case 0x0020: visitor.OnVariableLeOp(node); break;
				case 0x0021: visitor.OnVariableCallArgs(node); break;
				case 0x0022: visitor.OnVariableCallBracket(node); break;
				case 0x0023: visitor.OnVariableFuncName(node); break;
				case 0x0024: visitor.OnVariableCall(node); break;
				case 0x0025: visitor.OnVariableTrimLeading(node); break;
				case 0x0026: visitor.OnVariableTrimTrailing(node); break;
				case 0x0027: visitor.OnVariableTrimBoth(node); break;
				case 0x0028: visitor.OnVariableTrimSpecification(node); break;
				case 0x0029: visitor.OnVariableTrimCall(node); break;
				case 0x002A: visitor.OnVariableFuncCall(node); break;
				case 0x002B: visitor.OnVariableBracketExpr(node); break;
				case 0x002C: visitor.OnVariableSimpleExpr(node); break;
				case 0x002D: visitor.OnVariableUnaryExpr(node); break;
				case 0x002E: visitor.OnVariableMulExpr(node); break;
				case 0x002F: visitor.OnVariableAddExpr(node); break;
				case 0x0030: visitor.OnVariableConcatExpr(node); break;
				case 0x0031: visitor.OnVariableComExpr(node); break;
				case 0x0032: visitor.OnVariableRelExpr(node); break;
				case 0x0033: visitor.OnVariableNotOp(node); break;
				case 0x0034: visitor.OnVariableAndOp(node); break;
				case 0x0035: visitor.OnVariableOrOp(node); break;
				case 0x0036: visitor.OnVariableUxBoolExpr(node); break;
				case 0x0037: visitor.OnVariableAndBoolExpr(node); break;
				case 0x0038: visitor.OnVariableOrBoolExpr(node); break;
				case 0x0039: visitor.OnVariableExpr(node); break;
				case 0x003A: visitor.OnVariableBoolExpr(node); break;
				case 0x003B: visitor.OnVariableSetQuantifier(node); break;
				case 0x003C: visitor.OnVariableAsrerisk(node); break;
				case 0x003D: visitor.OnVariableAggrCallBracket(node); break;
				case 0x003E: visitor.OnVariableAggrFunc(node); break;
				case 0x003F: visitor.OnVariableAggrCountAll(node); break;
				case 0x0040: visitor.OnVariableAggrCall(node); break;
				case 0x0041: visitor.OnVariableSelectSublist(node); break;
				case 0x0042: visitor.OnVariableExprAlias(node); break;
				case 0x0043: visitor.OnVariableField(node); break;
				case 0x0044: visitor.OnVariableSelectList(node); break;
				case 0x0045: visitor.OnVariableTableExpression(node); break;
				case 0x0046: visitor.OnVariableWhereClause(node); break;
				case 0x0047: visitor.OnVariableFromClause(node); break;
				case 0x0048: visitor.OnVariableTableReferenceList(node); break;
				case 0x0049: visitor.OnVariableTableReference(node); break;
				case 0x004A: visitor.OnVariableTablePrimary(node); break;
				case 0x004B: visitor.OnVariableJoinedTable(node); break;
				case 0x004C: visitor.OnVariableAutoJoin(node); break;
				case 0x004D: visitor.OnVariableQualifiedJoin(node); break;
				case 0x004E: visitor.OnVariableJoinType(node); break;
				case 0x004F: visitor.OnVariableOuterJoinType(node); break;
				case 0x0050: visitor.OnVariableJoinSpecification(node); break;
				case 0x0051: visitor.OnVariableJoinCondition(node); break;
				case 0x0052: visitor.OnVariableSelect(node); break;
				case 0x0053: visitor.OnVariableOrderBy(node); break;
				case 0x0054: visitor.OnVariableSortSpecificationList(node); break;
				case 0x0055: visitor.OnVariableSortSpecification(node); break;
				case 0x0056: visitor.OnVariableOrderingSpecification(node); break;
				case 0x0057: visitor.OnVariableGroupBy(node); break;
				case 0x0058: visitor.OnVariableGroupSpecificationList(node); break;
				case 0x0059: visitor.OnVariableGroupSpecification(node); break;
				case 0x005A: visitor.OnVariableLimitOffset(node); break;
				case 0x005B: visitor.OnVariableLimit(node); break;
				case 0x005C: visitor.OnVariableOffset(node); break;
				case 0x005D: visitor.OnVariableStatement(node); break;
				case 0x005E: visitor.OnVariableRoot(node); break;
			}
		}
	}
}
