call push Gehtsoft.EF.Entities.1.9.2.nupkg
call push Gehtsoft.EF.Utils.1.9.2.nupkg
call push Gehtsoft.EF.Db.SqlDb.1.9.2.nupkg
call push Gehtsoft.EF.Db.SqlDb.OData.1.9.2.nupkg
call push Gehtsoft.EF.Db.SqlDb.Sql.1.9.2.nupkg
call push Gehtsoft.EF.FTS.1.9.2.nupkg
call push Gehtsoft.EF.Db.MssqlDb.1.9.2.nupkg
call push Gehtsoft.EF.Db.MysqlDb.1.9.2.nupkg
call push Gehtsoft.EF.Db.OracleDb.1.9.2.nupkg
call push Gehtsoft.EF.Db.PostgresDb.1.9.2.nupkg
call push Gehtsoft.EF.Db.SqliteDb.1.9.2.nupkg
call push Gehtsoft.EF.Bson.1.9.2.nupkg
call push Gehtsoft.EF.MongoDb.1.9.2.nupkg
